Added stil-id to user
fsek/WebWebWeb pull request #100
Opened 2024-12-04 18:02 UTC by Trobbi

2024-12-21 18:56 UTC, Equasa reviewed
Ser generellt bra ut men borde fixa MeUpdate

2024-12-21 18:56 UTC, Equasa commented on api_schemas/user_schemas.py
> +    stil_id: str
shouldnt it be str | None = None here?

2024-12-21 18:57 UTC, Equasa requested changes
Ser generellt riktigt bra ut men borde fixa MeUpdate

2024-12-22 02:01 UTC, Trobbi commented on api_schemas/user_schemas.py
> +    stil_id: str
Borde vara gjort om jag förstod rätt?

2024-12-22 09:39 UTC, Equasa approved these changes
LGTM

2024-12-22 09:39 UTC, merged