Added tags for images, events and news
fsek/WebWebWeb pull request #103
Opened 2024-12-11 17:09 UTC by OlleSettergren

Anything else that needs to be added at this stage?

2024-12-21 19:03 UTC, Equasa requested changes
Generellt sätt en snygg pull request, dock krävs det mer arbete genom att bygga upp fler tables då detta skulle skapa galet mycket redundant utrymme i våran databas. Jag vill ha tables så som NewsTags osv istället

2024-12-21 19:03 UTC, Equasa commented on db_models/tag_model.py
> +    color: Mapped[str] = mapped_column(String(7))  # Defined as #ff0000 for example
kan vara värt att kolla på detta: https://docs.pydantic.dev/2.0/usage/types/extra_types/color_types/

2024-12-21 19:03 UTC, Equasa commented on db_models/tag_model.py
> +    events: AssociationProxy[list["Event_DB"]] = association_proxy(
Detta är inte rätt implementerat, ska vara kopplat på annat sätt, skulle läsa att du vill göra typ en EventTags model också istället

2024-12-21 19:03 UTC, Equasa commented on db_models/tag_model.py
> +    news: AssociationProxy[list["News_DB"]] = association_proxy(target_collection="news_tags", attr="tag", init=False)
samma sak som ovam

2024-12-21 19:03 UTC, Equasa commented on db_models/tag_model.py
> +    images: AssociationProxy[list["Img_DB"]] = association_proxy(target_collection="image_tags", attr="tag", init=False)
samma sak igen

2024-12-21 19:38 UTC, OlleSettergren commented
> Generellt sätt en snygg pull request, dock krävs det mer arbete genom att bygga upp fler tables då detta skulle skapa galet mycket redundant utrymme i våran databas. Jag vill ha tables så som NewsTags osv istället

Hmm. Varje tag-modell kommer väl i princip bli ekvivalent med de andra förutom att man byter ut typen av lista? Finns det nåt smidigt sätt att göra det utan att behöva göra massa copy paste?

Som jag förstår det blir det samma problem sen när man väl ska definiera varje individuell tag, alltså att lägga in t.ex. "nollning" och "styrelsen" både som EventTag, ImageTag, NewsTag osv. Samma sak när man ska hämta allt innehåll kopplat till en viss tag.

2024-12-22 09:47 UTC, Equasa commented
> > Generellt sätt en snygg pull request, dock krävs det mer arbete genom att bygga upp fler tables då detta skulle skapa galet mycket redundant utrymme i våran databas. Jag vill ha tables så som NewsTags osv istället
> 
> Hmm. Varje tag-modell kommer väl i princip bli ekvivalent med de andra förutom att man byter ut typen av lista? Finns det nåt smidigt sätt att göra det utan att behöva göra massa copy paste?
> 
> Som jag förstår det blir det samma problem sen när man väl ska definiera varje individuell tag, alltså att lägga in t.ex. "nollning" och "styrelsen" både som EventTag, ImageTag, NewsTag osv. Samma sak när man ska hämta allt innehåll kopplat till en viss tag.

Asså grejen är att AssociationProxy löser inte alla problem åt oss utan man behöver skapa ett mellanliggande table...
Läs detta: https://chatgpt.com/share/6767e031-5698-8004-a2f0-a1408c7dafe8

2025-01-19 12:46 UTC, closed without merging