Added dev CORS policy and modified route id gen
fsek/WebWebWeb pull request #80
Opened 2024-09-30 16:04 UTC by maffe03

Added a CORS policy to allow for localhost development. Also changed route operation id to be less wordy and duplicated which will make codegen much nicer. :)

2024-10-01 07:46 UTC, Equasa requested changes
looks good, just need to change from environ

2024-10-01 07:46 UTC, Equasa commented on main.py
> +if environ.get("ENV") == "development":
byt ut environ mot getenv()

2024-10-01 07:46 UTC, Equasa commented on main.py
>      if environ.get("ENV") == "development":
byt till os.getenv()

2024-10-01 17:05 UTC, PelicanQ commented
Cool! This does however not guarantee unique operationId's. It takes the names of our functions.
Here I have one route in root router and one in user router. both function name `some_name`. In openapi.json, both have `some_name` as operationId. 
![image](https://github.com/user-attachments/assets/7d48b7bf-d84c-438c-ab73-1511430c5b61)
![image](https://github.com/user-attachments/assets/1912aeaa-5ee7-4e5c-acef-7b17e25d4834)

Is there a point to having nice short operationId's even if you won't be writing them explicitly?

2024-10-05 20:23 UTC, maffe03 commented
Yes you're right, OpenAPI requires operationIds to be unique. The latest commit should address this. It might not be the case for routes without tags, but I hope we add tags to all our routes anyways. (We currently have 4 test routes in main.py without tags but the rest do. Could probably add a prefix like 'base' otherwise?). 

With this commit it should be possible to do good, almost not janky, codegen on the frontend, while making sure ids (under different routers) are unique. I don't know if FastAPI has any protection against routes within a router having the same name. Does python forbid this? 

Atleast this is (almost) identical to the [guide](https://fastapi.tiangolo.com/advanced/generate-clients/#custom-generate-unique-id-function) on FastAPI.

2024-10-09 15:20 UTC, Equasa approved these changes

2024-10-09 15:21 UTC, merged