Nollningar + Äventyrsuppdrag + Grupper
fsek/WebWebWeb pull request #97
Opened 2024-12-04 16:59 UTC by Trobbi

2024-12-22 10:22 UTC, Equasa requested changes
Sjukt bra pull request! Märks att du har tänkt noggrant och bra! Jag har mest kommenterat på smågrejer samt:
for var, value in vars(data).items():
        setattr(nollning, var, value) if value else None
som jag tycker är superspännande. Fixa kommentarerna sen är detta en dunderrequest!

2024-12-22 10:22 UTC, Equasa commented on routes/adventure_mission_router.py
> +)
konstig response_model

2024-12-22 10:22 UTC, Equasa commented on routes/group_router.py
> +    "/delete/{id}", dependencies=[Permission.require("manage", "Groups")], response_model=dict[str, str]
konstigt igen men har inte kommit till implementationen

2024-12-22 10:22 UTC, Equasa commented on routes/nollning_router.py
> +"""
ta bort

2024-12-22 10:22 UTC, Equasa commented on services/adventure_mission_service.py
> +    if len(data.title) > MAX_ADVENTURE_MISSION_NAME:
tror detta checkas automatiskt mha schemas om du har satt Annotated[str, MAX_ADVENT....] men detta fungerar också

2024-12-22 10:22 UTC, Equasa commented on services/adventure_mission_service.py
> +    for var, value in vars(data).items():
crazy, fungerar detta för isf är det ny standard på hur vi implementerar sånt här!

2024-12-22 10:22 UTC, Equasa commented on services/group_service.py
> +
här använder du try catch men inte där uppe, varför? vi måste bestämma oss för ett sätt att göra det på!

2024-12-22 10:22 UTC, Equasa commented on services/group_service.py
> +    if group1 == None:
kan vara if group1 istället

2024-12-22 10:22 UTC, Equasa commented on services/group_service.py
> +    try:
samma sak här, vi måste bestämma oss

2024-12-22 17:05 UTC, Trobbi commented on api_schemas/adventure_mission_schema.py
> +    points: str
Alla dem här som du kommenterade om de skulle vara ints funderade jag mycket över. Asså det beror lite på hur vi vill göra... 

Det brukar liksom vara så att folk lägger 1-5 poäng som beskrivningen över hur många poäng för att uppdraget ska kunna ha dynamisk poäng.

Hur vill vi göra här? Vi hade kunnat göra en many-many där man kopplar grupper till uppdraget och så innehåller den modellen som är imellan hur många poäng grupper har på det uppdraget. 

Eller har du någon idé?

2024-12-22 17:40 UTC, Trobbi commented on routes/adventure_mission_router.py
> +)
Response modellen ser ut så för att, som jag fattat det, parsas dicts som JSON när de kommer ut vilken det typ inte skulle göra om jag bara gav en str.

Det är till delete routen, så jag ger ba tillbaka ett meddelande att det lyckats. 

Vill vi ge ut något annat på delete routes?

2024-12-22 17:44 UTC, Trobbi commented on services/adventure_mission_service.py
> +    for var, value in vars(data).items():
Tror jag snodde detta någonstans ifrån lol, men från min (limited) testning så hittade jag inget problem med det.

2025-01-18 12:59 UTC, Trobbi commented on routes/adventure_mission_router.py
> +)
ResponseModel ska vara objektet som tagits bort.

2025-01-19 14:16 UTC, Equasa approved these changes
LGTM

2025-01-19 14:25 UTC, Equasa approved these changes
LGTM

2025-01-19 14:26 UTC, merged